# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'douban_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(989, 1438)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_head = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_head.setObjectName("comboBox_head")
        self.comboBox_head.addItem("")
        self.comboBox_head.addItem("")
        self.gridLayout.addWidget(self.comboBox_head, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 16, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.lineEdit_excel = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_excel.setObjectName("lineEdit_excel")
        self.gridLayout.addWidget(self.lineEdit_excel, 2, 1, 1, 1)
        self.comboBox_random_target = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_random_target.setObjectName("comboBox_random_target")
        self.comboBox_random_target.addItem("")
        self.comboBox_random_target.addItem("")
        self.gridLayout.addWidget(self.comboBox_random_target, 5, 1, 1, 1)
        self.comboBox_star = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_star.setObjectName("comboBox_star")
        self.comboBox_star.addItem("")
        self.comboBox_star.addItem("")
        self.comboBox_star.addItem("")
        self.comboBox_star.addItem("")
        self.comboBox_star.addItem("")
        self.comboBox_star.addItem("")
        self.gridLayout.addWidget(self.comboBox_star, 6, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 8, 0, 1, 1)
        self.textBrowser_display = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_display.setObjectName("textBrowser_display")
        self.gridLayout.addWidget(self.textBrowser_display, 15, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 9, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 11, 0, 1, 1)
        self.lineEdit_movieurl = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_movieurl.setObjectName("lineEdit_movieurl")
        self.gridLayout.addWidget(self.lineEdit_movieurl, 10, 1, 1, 1)
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.gridLayout.addWidget(self.lineEdit_password, 9, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 7, 0, 1, 2)
        self.lineEdit_username = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.gridLayout.addWidget(self.lineEdit_username, 8, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 12, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 14, 1, 1, 1)
        self.textEdit_comment = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_comment.setObjectName("textEdit_comment")
        self.gridLayout.addWidget(self.textEdit_comment, 11, 1, 1, 1)
        self.textBrowser_info = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_info.setObjectName("textBrowser_info")
        self.gridLayout.addWidget(self.textBrowser_info, 1, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 10, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 2)
        self.lineEdit_time = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_time.setObjectName("lineEdit_time")
        self.gridLayout.addWidget(self.lineEdit_time, 12, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 15, 0, 1, 1)
        self.pushButton_loadexcel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_loadexcel.setObjectName("pushButton_loadexcel")
        self.gridLayout.addWidget(self.pushButton_loadexcel, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 13, 0, 1, 1)
        self.lineEdit_blacklist = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_blacklist.setObjectName("lineEdit_blacklist")
        self.gridLayout.addWidget(self.lineEdit_blacklist, 13, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 989, 45))
        self.menubar.setObjectName("menubar")
        self.menu_v1 = QtWidgets.QMenu(self.menubar)
        self.menu_v1.setObjectName("menu_v1")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menu_v1.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox_head.setItemText(0, _translate("MainWindow", "有头浏览"))
        self.comboBox_head.setItemText(1, _translate("MainWindow", "无头浏览"))
        self.pushButton.setText(_translate("MainWindow", "开始"))
        self.label_7.setText(_translate("MainWindow", "是否显示浏览器"))
        self.label_11.setText(_translate("MainWindow", "EXCEL账号路径"))
        self.comboBox_random_target.setItemText(0, _translate("MainWindow", "随机电影"))
        self.comboBox_random_target.setItemText(1, _translate("MainWindow", "随机电视剧"))
        self.comboBox_star.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_star.setItemText(1, _translate("MainWindow", "5"))
        self.comboBox_star.setItemText(2, _translate("MainWindow", "4"))
        self.comboBox_star.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_star.setItemText(4, _translate("MainWindow", "2"))
        self.comboBox_star.setItemText(5, _translate("MainWindow", "1"))
        self.label_3.setText(_translate("MainWindow", "用户名"))
        self.label_6.setText(_translate("MainWindow", "随机方式"))
        self.label_4.setText(_translate("MainWindow", "指定密码"))
        self.label_12.setText(_translate("MainWindow", "指定评论内容"))
        self.label_10.setText(_translate("MainWindow", "                         人工模式"))
        self.label_8.setText(_translate("MainWindow", "指定星级"))
        self.label_13.setText(_translate("MainWindow", "发布间隔时间（秒）"))
        self.textBrowser_info.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1.EXCEL账号路径如：<span style=\" font-family:\'JetBrains Mono,monospace\'; color:#000000;\">D:\\Jupyter\\</span><span style=\" font-family:\'宋体,monospace\'; color:#000000;\">爬虫</span><span style=\" font-family:\'JetBrains Mono,monospace\'; color:#000000;\">\\</span><span style=\" font-family:\'宋体,monospace\'; color:#000000;\">豆瓣自动发帖</span><span style=\" font-family:\'JetBrains Mono,monospace\'; color:#000000;\">\\version1\\dist\\</span><span style=\" font-family:\'宋体,monospace\'; color:#000000;\">账号</span><span style=\" font-family:\'JetBrains Mono,monospace\'; color:#000000;\">.xlsx</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono,monospace\'; color:#000000;\">或者直接点击按钮添加路径</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2.是否显示浏览器：有头浏览：显示。无头浏览：不显示。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">随机模式</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1.如果不输入指定的用户名和密码，程序将从excel中随机抽取账户和文案进行发布。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2.如果不输入指定电影url，程序将随机抽取电影或电视剧进行评论</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3.默认随机选取电影</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4.指定星级<span style=\" font-weight:600;\">0</span>的含义是指：<span style=\" font-weight:600;\">匹配目前分数</span>；其余1-5则按1-5星级给分</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">人工模式</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1.用户名：填写了用户名与密码，则自动切换为人工模式</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2.密码：必填</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3.指定电影url:请输入电影评论页的url，如：</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            https://movie.douban.com/subject/30483667/</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4.指定评论内容：必填</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5.发布时间间隔：如60-300，用-分开，在60秒和300秒之间随机选</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">6.黑名单，如35324548，35324549，35324542 用逗号分开</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "指定电影url"))
        self.label_9.setText(_translate("MainWindow", "                         随机模式"))
        self.label_2.setText(_translate("MainWindow", "运行详情"))
        self.pushButton_loadexcel.setText(_translate("MainWindow", "读取账户excel"))
        self.label.setText(_translate("MainWindow", "黑名单"))
        self.menu_v1.setTitle(_translate("MainWindow", "豆瓣自动评论v1"))
        self.menu.setTitle(_translate("MainWindow", "帮助"))
